
build_windows:
    stage: build
    tags:
        - windows
    script: 
        - cd upload-client
        - C:\cygwin64\bin\bash.exe build-windows.sh        
    artifacts:
        paths:
        - upload-client.zip
        - upload-client-setup.exe
    
build_linux:
    image: ubuntu:14.04
    stage: build
    tags:
        - linux
    script: 
        - apt-get update
        - apt-get install -qy qt5-default qt5-qmake qtbase5-dev git cmake make build-essential
        - cd upload-client
        - mkdir build_linux && cd build_linux
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="./"
        - make all install
        - cp -arv upload-client ../../upload-client-x64
    artifacts:
        paths:
        - upload-client-x64

build_macos:
    stage: build
    tags:
        - macos
    script: 
        - cd upload-client
        - mkdir build_macos && cd build_macos
        - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="./"
        - make all install
        - macdeployqt upload-client.app -always-overwrite -dmg
        - cp -av *.dmg ../../
    artifacts:
        paths:
        - upload-client.dmg
